### ISSUE TITLE
added shell script to git repo, does not execute on server

### ISSUE THREAD

**Issue by jamesecorrenti** [tratda/sturdy-octo-system#2]
added a script to your admin repo (executes ps -aux) and it did not display when I connected to the server

**Comment by tratda** [comment]
The server is running an extremely restricted docker container. If the container is run without detached mode using the command "docker run -p 22:22 -p 443:443 git_web_server" error messages from the shell can be seen. The command nc for example is not on the server, and needs to be installed before it could be run. It's absence from the machine is verified via an examination of standard error. What commands were you attempting to run on the server?

**Comment by tratda** [comment]
This issue arose due to config which prevented subsequent pushes from accurately being reflected in the local git repo. This has been mitigated by reseting the web repo before attempting to repull from the server. This patch has been applied in a66761f
